const truyenConGai = [
    {   
        id: 0,
        comicTittle: 'Luôn Có Yêu Quái',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai',
        comicImage: 'https://3.bp.blogspot.com/-OoE5hS24f6U/Wpqy6tSCAcI/AAAAAAAAQ-4/bDDZ8IunsW47AtiPPXVlue1mK3b4Hj4yQCHMYCw/luon-co-yeu-quai',
        comicView: '982.067',
        comicIntro: {
            infoImage: 'https://3.bp.blogspot.com/-OoE5hS24f6U/Wpqy6tSCAcI/AAAAAAAAQ-4/bDDZ8IunsW47AtiPPXVlue1mK3b4Hj4yQCHMYCw/luon-co-yeu-quai',
            infoName: 'Luôn Có Yêu Quái',
            infoOtherName: '',
            infoAuthor: '',
            infoStatus: 'Đang tiến hành',
            infoKind: 'Manhua - Ngôn Tình - Truyện Màu',
            infoView: '998.176',
            infoFollow: '5.654',
            infoContent: '...'
        },
        comicChapters: [
        { comicChapter: 'Chapter 83',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-83/417533',
            comicDateUpdate: '2 ngày trước',
            comicView: '2.876',
            comicImages: [ 
                'https://3.bp.blogspot.com/-QHumRVkkz3Y/W9yDt77VW5I/AAAAAAAA7Dc/yV7G-5y8kIouCgoOvv1DyA_hhsTWj6YOQCLcBGAs/s0/0%281%29.jpg',
                'https://3.bp.blogspot.com/-LNxk7_5c8xs/W9yDt316y6I/AAAAAAAA7Dg/SIKEUX0rZkA7HtPSKvplo3CmdxQISRWGACLcBGAs/s0/0%282%29.jpg',
                'https://3.bp.blogspot.com/-nxI_M85CrhI/W9yDt5c3v6I/AAAAAAAA7Dk/GoFj74SKglEcTH_kwVjwyVP0cCKVtj0DACLcBGAs/s0/0%283%29.jpg',
                'https://3.bp.blogspot.com/-9DawAXqOfa0/W9yDu_4jx5I/AAAAAAAA7Do/yKAu4yZP2-sB-DrCYttYspjNa7TpOsMrQCLcBGAs/s0/0%284%29.jpg',
                'https://3.bp.blogspot.com/-sdfUT-IAmG8/W9yDvCUykKI/AAAAAAAA7Ds/Eh6LULknZ4UpLkfPP48n0_JM9hVMmrl3QCLcBGAs/s0/0%285%29.jpg',
                'https://3.bp.blogspot.com/-EEURQXm__Lk/W9yDvY5IXWI/AAAAAAAA7Dw/wPD7iB9m93coOVTDDpx4VXOakIAeSNfswCLcBGAs/s0/0%286%29.jpg',
                'https://3.bp.blogspot.com/-U2GkVR6ZYAE/W9yDwTchTjI/AAAAAAAA7D0/ZlTDkGSX36Q2sm0PINGHNqt2Iallt3tGACLcBGAs/s0/0%287%29.jpg',
                'https://3.bp.blogspot.com/-0d9aOlkutKM/W9yDwqjDd7I/AAAAAAAA7D4/GVlUEslOz4oe7sb2ULH8VKcVSUhSVYS-gCLcBGAs/s0/0%288%29.jpg' 
            ]
        },
        { comicChapter: 'Chapter 82',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-82/416624',
            comicDateUpdate: '21:34 30/10',
            comicView: '3.461',
            comicImages: [ 
                'https://ngonphongcomics.com/wp-content/uploads/2017/11/SqNW9UG.jpg',
                'https://3.bp.blogspot.com/-wG_gltRronI/W9hrgVqDlhI/AAAAAAAA6yA/UkErb1DSS6Me4DHMpcPp_scH7sYu2xE6QCLcBGAs/s0/0%281%29.jpg',
                'https://3.bp.blogspot.com/-rxMMwOBMAws/W9hrgaShSYI/AAAAAAAA6x8/R7PjO39T9egVx9a2fyYgqQdmbuPUejvXwCLcBGAs/s0/0%282%29.jpg',
                'https://3.bp.blogspot.com/-QL_F6a8NAZY/W9hrh7Y4iJI/AAAAAAAA6yE/M2pOd9zGiNseO59VQvdLiQ-LHTtAZBsfACLcBGAs/s0/0%283%29.jpg',
                'https://3.bp.blogspot.com/-KmquH9Dm5nc/W9hriLOTYRI/AAAAAAAA6yI/LcoSlzbhepoK1CLQ5tCuec-wX8_fAiObwCLcBGAs/s0/0%284%29.jpg',
                'https://3.bp.blogspot.com/-rNMRQ16zhAQ/W9hriJDzVjI/AAAAAAAA6yM/Yqk05esHmVYnQ9XJdRovHDP5tT-bLLDYACLcBGAs/s0/0%285%29.jpg',
                'https://3.bp.blogspot.com/-tHblmD5eXps/W9hrja5Zv5I/AAAAAAAA6yQ/3PBI6H4XhV8OH4Ri7vhKBQPvYpCsroGkACLcBGAs/s0/0%286%29.jpg',
                'https://3.bp.blogspot.com/-eHoGIF1YsEo/W9hrjRQpoUI/AAAAAAAA6yU/NsSCwpdk99M6vmSGxkqOheJhKBZKS3arwCLcBGAs/s0/0%287%29.jpg',
                'https://3.bp.blogspot.com/-K64Jkx1UlHE/W9hrjjdr_zI/AAAAAAAA6yY/lSt9jQBz1u8MiliAi-5DWAj4bhm-SXV3gCLcBGAs/s0/0%288%29.jpg',
                'https://3.bp.blogspot.com/-PMpoid7O1uc/W9hrkvet43I/AAAAAAAA6yc/OUk0UjCZTm0VX7NuXQY-nt1HjM2QsY0pwCLcBGAs/s0/0%289%29.jpg',
                'https://3.bp.blogspot.com/-vpSz2NWYe7M/W9hrgV7SmxI/AAAAAAAA6x4/aap_pQ3Ulik4CrzYEunQc34-wUaQpsouQCLcBGAs/s0/0%2810%29.jpg' 
            ]
        },
        { comicChapter: 'Chapter 81',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-81/414342',
            comicDateUpdate: '19:50 25/10',
            comicView: '4.474' },
        { comicChapter: 'Chapter 80',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-80/413127',
            comicDateUpdate: '21:20 20/10',
            comicView: '4.760' },
        { comicChapter: 'Chapter 79',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-79/407010',
            comicDateUpdate: '22:22 17/09',
            comicView: '6.104' },
        { comicChapter: 'Chapter 78',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-78/405861',
            comicDateUpdate: '15:36 11/09',
            comicView: '6.069' },
        { comicChapter: 'Chapter 77',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-77/404575',
            comicDateUpdate: '22:03 04/09',
            comicView: '6.612' },
        { comicChapter: 'Chapter 76',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-76/401309',
            comicDateUpdate: '22:34 17/08',
            comicView: '7.081' },
        { comicChapter: 'Chapter 75',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-75/399822',
            comicDateUpdate: '09:00 13/08',
            comicView: '6.923' },
        { comicChapter: 'Chapter 74',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-74/398506',
            comicDateUpdate: '11:55 06/08',
            comicView: '6.747' },
        { comicChapter: 'Chapter 73',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-73/395608',
            comicDateUpdate: '20:09 24/07',
            comicView: '7.319' },
        { comicChapter: 'Chapter 72',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-72/394645',
            comicDateUpdate: '19:02 19/07',
            comicView: '7.054' },
        { comicChapter: 'Chapter 71',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-71/394018',
            comicDateUpdate: '09:27 17/07',
            comicView: '7.237' },
        { comicChapter: 'Chapter 70',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-70/386509',
            comicDateUpdate: '11:05 11/06',
            comicView: '8.566' },
        { comicChapter: 'Chapter 69',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-69/385207',
            comicDateUpdate: '10:53 04/06',
            comicView: '7.939' },
        { comicChapter: 'Chapter 68',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-68/384507',
            comicDateUpdate: '22:03 31/05',
            comicView: '8.351' },
        { comicChapter: 'Chapter 67',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-67/383165',
            comicDateUpdate: '20:25 24/05',
            comicView: '8.544' },
        { comicChapter: 'Chapter 66',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-66/383049',
            comicDateUpdate: '21:38 23/05',
            comicView: '8.245' },
        { comicChapter: 'Chapter 65',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-65/382509',
            comicDateUpdate: '20:09 20/05',
            comicView: '8.246' },
        { comicChapter: 'Chapter 64',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-64/381615',
            comicDateUpdate: '20:38 15/05',
            comicView: '8.576' },
        { comicChapter: 'Chapter 63',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-63/380468',
            comicDateUpdate: '19:17 09/05',
            comicView: '8.535' },
        { comicChapter: 'Chapter 62',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-62/379682',
            comicDateUpdate: '17:02 04/05',
            comicView: '8.454' },
        { comicChapter: 'Chapter 61',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-61/379587',
            comicDateUpdate: '20:42 03/05',
            comicView: '9.024' },
        { comicChapter: 'Chapter 60',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-60/379193',
            comicDateUpdate: '16:36 30/04',
            comicView: '9.405' },
        { comicChapter: 'Chapter 59',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-59/378993',
            comicDateUpdate: '13:22 29/04',
            comicView: '8.580' },
        { comicChapter: 'Chapter 58',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-58/378681',
            comicDateUpdate: '15:51 26/04',
            comicView: '8.675' },
        { comicChapter: 'Chapter 57',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-57/376052',
            comicDateUpdate: '21:23 09/04',
            comicView: '9.106' },
        { comicChapter: 'Chapter 56',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-56/375758',
            comicDateUpdate: '09:58 08/04',
            comicView: '8.784' },
        { comicChapter: 'Chapter 55',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-55/372234',
            comicDateUpdate: '20:25 12/03',
            comicView: '9.814' },
        { comicChapter: 'Chapter 54',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-54/371398',
            comicDateUpdate: '22:32 06/03',
            comicView: '10.122' },
        { comicChapter: 'Chapter 53',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-53/370885',
            comicDateUpdate: '21:34 03/03',
            comicView: '9.908' },
        { comicChapter: 'Chapter 52',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-52/370075',
            comicDateUpdate: '16:14 28/02',
            comicView: '10.037' },
        { comicChapter: 'Chapter 51',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-51/369983',
            comicDateUpdate: '22:08 27/02',
            comicView: '9.406' },
        { comicChapter: 'Chapter 50',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-50/369369',
            comicDateUpdate: '09:50 24/02',
            comicView: '9.744' },
        { comicChapter: 'Chapter 49',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-49/367091',
            comicDateUpdate: '21:50 10/02',
            comicView: '8.641' },
        { comicChapter: 'Chapter 48',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-48/366359',
            comicDateUpdate: '13:06 04/02',
            comicView: '8.525' },
        { comicChapter: 'Chapter 47',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-47/365586',
            comicDateUpdate: '14:11 28/01',
            comicView: '8.503' },
        { comicChapter: 'Chapter 46',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-46/365194',
            comicDateUpdate: '18:44 24/01',
            comicView: '8.823' },
        { comicChapter: 'Chapter 45',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-45/363373',
            comicDateUpdate: '09:18 13/01',
            comicView: '8.778' },
        { comicChapter: 'Chapter 44',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-44/362025',
            comicDateUpdate: '20:46 04/01',
            comicView: '8.655' },
        { comicChapter: 'Chapter 43',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-43/360453',
            comicDateUpdate: '24/12/17',
            comicView: '8.791' },
        { comicChapter: 'Chapter 42',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-42/358552',
            comicDateUpdate: '12/12/17',
            comicView: '8.950' },
        { comicChapter: 'Chapter 41',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-41/357694',
            comicDateUpdate: '06/12/17',
            comicView: '9.748' },
        { comicChapter: 'Chapter 40',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-40/355794',
            comicDateUpdate: '24/11/17',
            comicView: '10.289' },
        { comicChapter: 'Chapter 39',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-39/353138',
            comicDateUpdate: '04/11/17',
            comicView: '9.356' },
        { comicChapter: 'Chapter 38',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-38/352743',
            comicDateUpdate: '31/10/17',
            comicView: '9.544' },
        { comicChapter: 'Chapter 37',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-37/351923',
            comicDateUpdate: '23/10/17',
            comicView: '9.808' },
        { comicChapter: 'Chapter 36',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-36/351704',
            comicDateUpdate: '21/10/17',
            comicView: '10.433' },
        { comicChapter: 'Chapter 35',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-35/350178',
            comicDateUpdate: '06/10/17',
            comicView: '10.794' },
        { comicChapter: 'Chapter 34',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-34/346555',
            comicDateUpdate: '07/09/17',
            comicView: '10.492' },
        { comicChapter: 'Chapter 33',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-33/346456',
            comicDateUpdate: '06/09/17',
            comicView: '10.721' },
        { comicChapter: 'Chapter 32',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-32/346340',
            comicDateUpdate: '05/09/17',
            comicView: '11.055' },
        { comicChapter: 'Chapter 31',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-31/346144',
            comicDateUpdate: '04/09/17',
            comicView: '11.548' },
        { comicChapter: 'Chapter 30',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-30/345990',
            comicDateUpdate: '03/09/17',
            comicView: '12.474' },
        { comicChapter: 'Chapter 29',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-29/345863',
            comicDateUpdate: '02/09/17',
            comicView: '12.138' },
        { comicChapter: 'Chapter 28',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-28/345721',
            comicDateUpdate: '01/09/17',
            comicView: '12.391' },
        { comicChapter: 'Chapter 27',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-27/344611',
            comicDateUpdate: '23/08/17',
            comicView: '12.979' },
        { comicChapter: 'Chapter 26',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-26/344449',
            comicDateUpdate: '22/08/17',
            comicView: '13.613' },
        { comicChapter: 'Chapter 25',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-25/344311',
            comicDateUpdate: '21/08/17',
            comicView: '14.371' },
        { comicChapter: 'Chapter 24',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-24/341414',
            comicDateUpdate: '01/08/17',
            comicView: '14.152' },
        { comicChapter: 'Chapter 23',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-23/341413',
            comicDateUpdate: '01/08/17',
            comicView: '13.764' },
        { comicChapter: 'Chapter 22',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-22/341412',
            comicDateUpdate: '01/08/17',
            comicView: '13.821' },
        { comicChapter: 'Chapter 21',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-21/341161',
            comicDateUpdate: '31/07/17',
            comicView: '14.023' },
        { comicChapter: 'Chapter 20',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-20/341160',
            comicDateUpdate: '31/07/17',
            comicView: '14.051' },
        { comicChapter: 'Chapter 19',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-19/341162',
            comicDateUpdate: '31/07/17',
            comicView: '13.007' },
        { comicChapter: 'Chapter 18',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-18/339800',
            comicDateUpdate: '22/07/17',
            comicView: '13.623' },
        { comicChapter: 'Chapter 17',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-17/339799',
            comicDateUpdate: '22/07/17',
            comicView: '13.566' },
        { comicChapter: 'Chapter 16',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-16/339675',
            comicDateUpdate: '21/07/17',
            comicView: '13.967' },
        { comicChapter: 'Chapter 15',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-15/339426',
            comicDateUpdate: '20/07/17',
            comicView: '14.707' },
        { comicChapter: 'Chapter 14',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-14/335476',
            comicDateUpdate: '23/06/17',
            comicView: '14.378' },
        { comicChapter: 'Chapter 13',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-13/335475',
            comicDateUpdate: '23/06/17',
            comicView: '14.337' },
        { comicChapter: 'Chapter 12',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-12/335474',
            comicDateUpdate: '23/06/17',
            comicView: '15.554' },
        { comicChapter: 'Chapter 11',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-11/335381',
            comicDateUpdate: '22/06/17',
            comicView: '16.731' },
        { comicChapter: 'Chapter 10',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-10/335380',
            comicDateUpdate: '22/06/17',
            comicView: '18.146' },
        { comicChapter: 'Chapter 9',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-9/335379',
            comicDateUpdate: '22/06/17',
            comicView: '17.415' },
        { comicChapter: 'Chapter 8',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-8/328134',
            comicDateUpdate: '15/06/17',
            comicView: '18.595' },
        { comicChapter: 'Chapter 7',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-7/327902',
            comicDateUpdate: '13/06/17',
            comicView: '19.385' },
        { comicChapter: 'Chapter 6',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-6/327824',
            comicDateUpdate: '13/06/17',
            comicView: '21.215' },
        { comicChapter: 'Chapter 5',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-5/327547',
            comicDateUpdate: '11/06/17',
            comicView: '24.256' },
        { comicChapter: 'Chapter 4',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-4/323935',
            comicDateUpdate: '14/05/17',
            comicView: '27.559' },
        { comicChapter: 'Chapter 3',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-3/323934',
            comicDateUpdate: '14/05/17',
            comicView: '30.162' },
        { comicChapter: 'Chapter 2',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-2/323933',
            comicDateUpdate: '14/05/17',
            comicView: '35.770' },
        { comicChapter: 'Chapter 1',
            comicChapterLink: 'http://www.nettruyen.com/truyen-tranh/luon-co-yeu-quai/chap-1/323932',
            comicDateUpdate: '14/05/17',
            comicView: '59.792' 
        }]
    },
    {   id: 1,
        comicTittle: 'Mùa Hè Của Tổng Tài',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/mua-he-cua-tong-tai',
        comicImage: 'https://3.bp.blogspot.com/-_yaT7mw7kQU/W09xym-DK2I/AAAAAAAAXaU/7XS96hvYGIkydB05dxz95fNmBAGE25BdgCHMYCw/mua-he-cua-tong-tai',
        comicView: '174.071' 
    },
    {   id: 2,
        comicTittle: 'Nữ hoàng Ai Cập',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/nu-hoang-ai-cap',
        comicImage: 'https://3.bp.blogspot.com/-ilal9FDyrZg/WzDymKxIN8I/AAAAAAAAV6o/uzGcCIH3DOouV28EuldDvDuyhX2k4rFxQCHMYCw/nu-hoang-ai-cap',
        comicView: '2.814.397' 
    },
    {   id: 3,
        comicTittle: 'Hào Môn Thiên Giới Tiền Thê',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/hao-mon-thien-gioi-tien-the',
        comicImage: 'https://3.bp.blogspot.com/-ZQRy2Hhpdgc/WBNE0nEVhlI/AAAAAAAAMoQ/Tx5SSQmGdzg/hao-mon-thien-gioi-tien-the.jpg',
        comicView: '18.263.077' 
    },
    {   id: 4,
        comicTittle: 'Ông Xã Thú Tính Đêm Đêm Gợi Tình',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/ong-xa-thu-tinh-dem-dem-goi-tinh',
        comicImage: 'https://3.bp.blogspot.com/-zgxxXKEQzr8/WvFFq-LhCmI/AAAAAAAATJQ/nROzMJ5BRCMoTOj1pk6y2p_b6IQEL1AagCHMYCw/ong-xa-thu-tinh-dem-dem-goi-tinh',
        comicView: '5.544.535' 
    },
    {   id: 5,
        comicTittle: 'Em Vẫn Còn Nhỏ',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/em-van-con-nho',
        comicImage: 'https://3.bp.blogspot.com/-jUFpA2qOx7k/WssVNTbsTpI/AAAAAAAASK0/j5j3VFcfP1IcT_6ONDVHa5QB8JhrwEuzgCHMYCw/em-van-con-nho',
        comicView: '3.059.758' 
    },
    {   id: 6,
        comicTittle: 'Mai Nữ Đồng Tiểu Nộ',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/mai-nu-dong-tieu-no',
        comicImage: 'https://3.bp.blogspot.com/-WyyzfVwAXlk/Wo9qkAWFq3I/AAAAAAAAODw/vBJeJGv45XAKAzt2EfFpBQP1r3x6pnTuQCHMYCw/mai-nu-dong-tieu-no',
        comicView: '1.001.617' 
    },
    {   id: 7,
        comicTittle: 'Dường như tình yêu đã đến',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/duong-nhu-tinh-yeu-da-den',
        comicImage: 'https://3.bp.blogspot.com/-4huhmraVmJY/Wysi3fL2afI/AAAAAAAAVrQ/if_YDZtFBS4_z-zEPiL2PniTqPZcnm-rwCHMYCw/duong-nhu-tinh-yeu-da-den',
        comicView: '1.567.382' 
    },
    {   id: 8,
        comicTittle: 'Du Thế Vô Song',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/du-the-vo-song',
        comicImage: 'https://3.bp.blogspot.com/-0kWAcyiWnTQ/WBNTUamN7AI/AAAAAAAAM0Y/VVJCsEiyw9o/du-the-vo-song.jpg',
        comicView: '378.232' 
    },
    {   id: 9,
        comicTittle: 'Nhất Dạ Nghiệt Tình: Cuồng Hôn Hào Môn Lão Công',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/nhat-da-nghiet-tinh-cuong-hon-hao-mon-lao-cong',
        comicImage: 'https://3.bp.blogspot.com/-nTsT503E_Ks/Wo6kLZQOXhI/AAAAAAAANUM/Ub2aesiwMM8zFTfUve5J4sQ9ZEx5x5rVgCHMYCw/nhat-da-nghiet-tinh-cuong-hon-hao-mon-lao-cong',
        comicView: '5.167.748' 
    },
    {   id: 10,    
        comicTittle: 'Thiếu soái của tôi chính là manh như vậy',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/thieu-soai-cua-toi-chinh-la-manh-nhu-vay',
        comicImage: 'https://3.bp.blogspot.com/-hjXabhMHAd8/W6h8vzfevgI/AAAAAAAAZtE/Mekiml6v3OQQRbFUvo3NOcRzahXxwzHFQCHMYCw/thieu-soai-cua-toi-chinh-la-manh-nhu-vay',
        comicView: '587.037' 
    },
    {   id: 11,
        comicTittle: 'Thứ Mà Thời Gian Đang Nợ anh Chính Là Em',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/thu-ma-thoi-gian-dang-no-anh-chinh-la-em',
        comicImage: 'https://3.bp.blogspot.com/-TAfySCyQx_s/W5XMYV9aaUI/AAAAAAAAZbI/4QrQ3E-GQ3MekaFW6A-YV6GZe628HXczQCHMYCw/thu-ma-thoi-gian-dang-no-anh-chinh-la-em',
        comicView: '580.179' 
    },
    {   id: 12,
        comicTittle: 'Bạn trai có điện từ',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/ban-trai-co-dien-tu',
        comicImage: 'https://3.bp.blogspot.com/-tZqmr9NbnI0/Wo9tPuibIxI/AAAAAAAAOpk/gukv5PycuJQUiqCy8vov_VIrBXOiCeYJQCHMYCw/ban-trai-co-dien-tu',
        comicView: '91.217' 
    },
    {   id: 13,
        comicTittle: 'Vương Gia ! Không nên a !',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/vuong-gia-khong-nen-a',
        comicImage: 'https://3.bp.blogspot.com/-XR_B6tlKrpw/Wo6kMfpEdjI/AAAAAAAANUU/tYdlCVB0DCcOmJ9nWxZ3hUs6BomPIVY6QCHMYCw/vuong-gia-khong-nen-a',
        comicView: '5.587.086' 
    },
    {   id: 14,
        comicTittle: 'Thần Y Đích Nữ',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/than-y-dich-nu',
        comicImage: 'https://3.bp.blogspot.com/-tV93uQiOXo0/WBNEoeuY3FI/AAAAAAAAMiI/Sz4G_igDato/than-y-dich-nu.jpg',
        comicView: '7.571.499' 
    },
    {   id: 15,
        comicTittle: 'Thông Linh Phi',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/thong-linh-phi',
        comicImage: 'https://3.bp.blogspot.com/-XEKoe-su61g/W3WopEyRDQI/AAAAAAAAY68/gt4oS7kV3pcBDxOtggPrDhlPaeIHwBv_QCHMYCw/thong-linh-phi',
        comicView: '27.706.753' 
    },
    {   id: 16,
        comicTittle: 'Minh Tinh Là Huyết Tộc',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/minh-tinh-la-huyet-toc',
        comicImage: 'https://3.bp.blogspot.com/-miPyhwi6igA/Wo9rUF-XuMI/AAAAAAAAOM0/kquvU4SEvzgnHNS5ARj7IYzKgrSAU4_rwCHMYCw/minh-tinh-la-huyet-toc',
        comicView: '502.715' 
    },
    {   id: 17,
        comicTittle: 'Đại Giá Thừa Tướng',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/dai-gia-thua-tuong',
        comicImage: 'https://3.bp.blogspot.com/-xFgW4fuPW-E/W1xvkZlMBeI/AAAAAAAAX1M/GhOu4Q7q0YgJqMwJoJHgwG4xY_5dnH2XACHMYCw/dai-gia-thua-tuong',
        comicView: '3.275.034' 
    },
    {   id: 18,
        comicTittle: 'Thiểm Hôn Kiều Thê',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/thiem-hon-kieu-the',
        comicImage: 'https://3.bp.blogspot.com/-kIN2gNiMqic/Wo9nou_2yJI/AAAAAAAANgE/OU9C5wI-uLUufUDK17YLEx356qqeytldwCHMYCw/thiem-hon-kieu-the',
        comicView: '6.996.878' 
    },
    {   id: 19,
        comicTittle: 'Cường Sủng Hào Môn Tiểu Manh Thê',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/cuong-sung-hao-mon-tieu-manh-the',
        comicImage: 'https://3.bp.blogspot.com/-sLuQDTtGi98/WvQNWuH0vjI/AAAAAAAATP8/3YEgVIy37jEeorepn1RE5_CqN_-brTkKwCHMYCw/cuong-sung-hao-mon-tieu-manh-the',
        comicView: '2.248.075' 
    },
    {   id: 20,
        comicTittle: 'Bạn Trai Tôi Là Cẩm Y Vệ 2',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/ban-trai-toi-la-cam-y-ve-2',
        comicImage: 'https://3.bp.blogspot.com/-M1ruq1KxQhc/W3KowUfeYAI/AAAAAAAAYvw/99YZYAyxa3wABnQ8MSELM10ieOzx30EJACHMYCw/ban-trai-toi-la-cam-y-ve-2',
        comicView: '365.546' 
    },
    {   id: 21,
        comicTittle: 'Tại Hạ Là Thần Tình Yêu',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/tai-ha-la-than-tinh-yeu',
        comicImage: 'https://3.bp.blogspot.com/-GMP5IGgehHs/WqSz0ga8QVI/AAAAAAAARR4/DqEtT8WXnlIJ5Y4nZ1lWF3zwOgDD19LtQCHMYCw/tai-ha-la-than-tinh-yeu',
        comicView: '151.848' 
    },
    {   id: 22,
        comicTittle: 'Con tim rung động 2',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/con-tim-rung-dong-2',
        comicImage: 'https://3.bp.blogspot.com/-51t1igA8PJM/WvFEfV7pD-I/AAAAAAAATH4/Hbysq2668UEM0PPGGlxNgWDqKdQ_SwIIACHMYCw/con-tim-rung-dong-2',
        comicView: '4.862.524' 
    },
    {   id: 23,
        comicTittle: 'Bí Mật Của Thiên Kim',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/bi-mat-cua-thien-kim',
        comicImage: 'https://3.bp.blogspot.com/-I4EORQ9mwSY/W5CEf6m9AGI/AAAAAAAAZXE/vwvgCUALZasqXNy_iWNYottJx3Xqn0ikwCHMYCw/bi-mat-cua-thien-kim',
        comicView: '583.384' 
    },
    {   id: 24,
        comicTittle: 'Nhân Chất Tình Nhân',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/nhan-chat-tinh-nhan',
        comicImage: 'https://3.bp.blogspot.com/-kgHjaI_K7GU/WqdkxteJZ3I/AAAAAAAARXI/ax6XxDzfl1kW-u88I4_GUDgUsi57OeyYwCHMYCw/nhan-chat-tinh-nhan',
        comicView: '419.561' 
    },
    {   id: 25,
        comicTittle: 'Yêu Phu! Xin Ngươi Hưu Ta Đi Mà!',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/yeu-phu-xin-nguoi-huu-ta-di-ma',
        comicImage: 'https://3.bp.blogspot.com/-LVlJVvZEmQM/Wo9nnzb4jnI/AAAAAAAANf4/smM37dtLvnUB2gLMlQ4K8oNU3wTg8AThwCHMYCw/yeu-phu-xin-nguoi-huu-ta-di-ma',
        comicView: '2.825.827' 
    },
    {   id: 26,
        comicTittle: 'Hãy Call trước khi bốc cháy',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/hay-call-truoc-khi-boc-chay',
        comicImage: 'https://3.bp.blogspot.com/-yt3WGdYx9qk/WwZkHRURzHI/AAAAAAAAUNg/mDj-GedqogQQdcBUH50GNq8EayjfnNhOgCHMYCw/hay-call-truoc-khi-boc-chay',
        comicView: '418.057' 
    },
    {   id: 27,
        comicTittle: 'Thời gian không phụ tình thâm',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/thoi-gian-khong-phu-tinh-tham',
        comicImage: 'https://3.bp.blogspot.com/-sCLkFYL5WuQ/WvplaQFgVAI/AAAAAAAATo4/ebCBrxXngHg4Rn5GyZ8au4LeOMLm3QSMgCHMYCw/thoi-gian-khong-phu-tinh-tham',
        comicView: '1.066.811' 
    },
    {   id: 28,
        comicTittle: 'Mặt nạ mê hoặc',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/mat-na-me-hoac',
        comicImage: 'https://3.bp.blogspot.com/-ePskCD0hLwI/WwrIkCKU7lI/AAAAAAAAUeA/8Q9SiJiMh5Y1-rNi9pAWmbzaeNTcZZVzACHMYCw/mat-na-me-hoac',
        comicView: '3.505.187' 
    },
    {   id: 29,
        comicTittle: 'Mật Ngọt Cấm Kỵ',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/mat-ngot-cam-ky',
        comicImage: 'https://3.bp.blogspot.com/-6cIfP71NSEM/Wo9t7mWwnuI/AAAAAAAAO0k/CMzqRo_8E0M6yvL30EOCb86VMXuhokvmgCHMYCw/mat-ngot-cam-ky',
        comicView: '631.043' 
    },
    {   id: 30,
        comicTittle: 'Thuần Tình Nha Đầu Hoả Lạt Lạt',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/thuan-tinh-nha-dau-hoa-lat-lat',
        comicImage: 'https://3.bp.blogspot.com/-SUTG9GHSVKs/W1YV-HHRdPI/AAAAAAAAXoM/BB9K74zSCts5ojMyD9EVeqRkQCxrXKONgCHMYCw/thuan-tinh-nha-dau-hoa-lat-lat',
        comicView: '51.725.677' 
    },
    {   id: 31,
        comicTittle: 'Bạn Trai Minh Tinh Bức Yêu',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/ban-trai-minh-tinh-buc-yeu',
        comicImage: 'https://3.bp.blogspot.com/-IflJ2NgvnDM/Wo9p39P-WvI/AAAAAAAAN24/WvPWygbYep4X3I1W1GsrB0iIn72YuzkrwCHMYCw/ban-trai-minh-tinh-buc-yeu',
        comicView: '989.763' 
    },
    {   id: 32,
        comicTittle: 'Nam Thần Của Tôi',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/nam-than-cua-toi',
        comicImage: 'https://3.bp.blogspot.com/-ez8X56ymPac/Wo9tT0EcUXI/AAAAAAAAOqw/2Bn1f9lnOIIC8wB88SkshzjRS40dSve7gCHMYCw/nam-than-cua-toi',
        comicView: '1.134.626' 
    },
    {   id: 33,
        comicTittle: '999 Nụ Hôn Bá Đạo Của Nam Thần',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/999-nu-hon-ba-dao-cua-nam-than',
        comicImage: 'https://3.bp.blogspot.com/-jR1bUMlUuoc/Wo9paA1hSTI/AAAAAAAANwg/2Pe0Bhw196A9gcE91OtLzt-lPTAgBx3RQCHMYCw/999-nu-hon-ba-dao-cua-nam-than',
        comicView: '14.167.911' 
    },
    {   id: 34,
        comicTittle: 'Thuốc Chữa Bệnh Vương Tử Của Tôi',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/thuoc-chua-benh-vuong-tu-cua-toi',
        comicImage: 'https://3.bp.blogspot.com/-cYASW9__s5M/WvnAN2P21zI/AAAAAAAATk8/S-NbmICzC5gLa3n6sdp5ypo2pe3V1LsHACHMYCw/thuoc-chua-benh-vuong-tu-cua-toi',
        comicView: '272.588' 
    },
    {   id: 35,
        comicTittle: 'Luyến Ái Sinh Tử Bộ',
        comicLink: 'http://www.nettruyen.com/truyen-tranh/luyen-ai-sinh-tu-bo',
        comicImage: 'https://3.bp.blogspot.com/-zT_MkxtYWE8/Wo9nnDFbFEI/AAAAAAAANfw/ndys2hkdqEMMuq2CJF2dybTuE4Yfc-nxQCHMYCw/luyen-ai-sinh-tu-bo',
        comicView: '2.623.074' 
    }];
export default truyenConGai;